"""
Database models for Wadiz Page Builder
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Boolean, JSON
from sqlalchemy.orm import relationship
from app.core.database import Base


class User(Base):
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    full_name = Column(String(255))
    is_active = Column(Boolean, default=True)
    is_superuser = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    projects = relationship("Project", back_populates="owner", cascade="all, delete-orphan")


class Project(Base):
    __tablename__ = "projects"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String(500), nullable=False)
    slug = Column(String(500), unique=True, index=True)
    category = Column(String(100))
    
    # Product Info
    product_name = Column(String(500))
    usp = Column(Text)  # Unique Selling Point
    target_audience = Column(Text)
    
    # AI Generated Content
    ai_copy = Column(Text)  # Main copy generated by AI
    ai_alternatives = Column(JSON)  # List of alternative copies
    
    # Page Structure
    page_structure = Column(JSON)  # Wadiz golden structure: intro, body, outro
    
    # Meta
    is_published = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    owner = relationship("User", back_populates="projects")
    images = relationship("Image", back_populates="project", cascade="all, delete-orphan")


class Image(Base):
    __tablename__ = "images"
    
    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id"), nullable=False)
    
    # Image Info
    filename = Column(String(500), nullable=False)
    original_filename = Column(String(500))
    file_url = Column(String(1000), nullable=False)  # S3/R2 URL
    file_size = Column(Integer)  # Bytes
    width = Column(Integer)
    height = Column(Integer)
    mime_type = Column(String(100))
    
    # Order in page
    position = Column(Integer, default=0)
    
    # Section (intro, body, outro)
    section = Column(String(50), default="body")
    
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    project = relationship("Project", back_populates="images")


class Template(Base):
    __tablename__ = "templates"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    category = Column(String(100))
    description = Column(Text)
    
    # Template structure
    structure = Column(JSON)  # HTML/CSS template structure
    
    # Stats
    usage_count = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
